### ISSUE TITLE
idgenerator flag redefined: log_dir

### ISSUE THREAD

**Issue by cloudscode** [Qihoo360/poseidon#10]
/src/github.com/Qihoo360/poseidon/dist/idgenerator/bin/idgenerator flag redefined: log_dir
panic: /src/github.com/Qihoo360/poseidon/dist/idgenerator/bin/idgenerator flag redefined: log_dir

goroutine 1 [running]:
panic(0x739b40, 0xc420011490)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
flag.(*FlagSet).Var(0xc4200581e0, 0x955f40, 0xc420011440, 0x7bcc29, 0x7, 0x7cdea2, 0x2f)
	/usr/local/go/src/flag/flag.go:791 +0x43e
flag.(*FlagSet).StringVar(0xc4200581e0, 0xc420011440, 0x7bcc29, 0x7, 0x0, 0x0, 0x7cdea2, 0x2f)
	/usr/local/go/src/flag/flag.go:694 +0x8b
flag.(*FlagSet).String(0xc4200581e0, 0x7bcc29, 0x7, 0x0, 0x0, 0x7cdea2, 0x2f, 0xc420011430)
	/usr/local/go/src/flag/flag.go:707 +0x90
flag.String(0x7bcc29, 0x7, 0x0, 0x0, 0x7cdea2, 0x2f, 0xc420049f28)
	/usr/local/go/src/flag/flag.go:714 +0x69
github.com/golang/glog.init()
	/root/goquery/src/github.com/golang/glog/glog_file.go:41 +0x148
github.com/zieckey/simgo.init()
	/root/goquery/src/github.com/zieckey/simgo/module_monitor.go:73 +0x76
main.init()
	/src/github.com/Qihoo360/poseidon/service/idgenerator/main.go:41 +0x33

**Comment by guojun1992** [comment]
@cloudscode Provide your operating system version and go language version thx

**Comment by cloudscode** [comment]
@guojun1992 
[root@localhost glog]# go version
go version go1.7.4 linux/amd64
[root@localhost glog]# uname -r
3.10.0-514.2.2.el7.x86_64
[root@localhost glog]# cat /proc/version 
Linux version 3.10.0-514.2.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Dec 6 23:06:41 UTC 2016
[root@localhost glog]#  cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)

**Comment by aidata** [comment]
I also reported the error. 

[root@H5 meta]# cat logs/run.log
/root/zb/src/github.com/Qihoo360/poseidon/dist/meta/bin/meta flag redefined: log_dir
panic: /root/zb/src/github.com/Qihoo360/poseidon/dist/meta/bin/meta flag redefined: log_dir

goroutine 1 [running]:
panic(0x742ec0, 0xc4201600c0)
	/usr/lib/golang/src/runtime/panic.go:500 +0x1a1
flag.(*FlagSet).Var(0xc420094180, 0x967fa0, 0xc420160070, 0x7c8c72, 0x7, 0x7da318, 0x2f)
	/usr/lib/golang/src/flag/flag.go:791 +0x43e
flag.(*FlagSet).StringVar(0xc420094180, 0xc420160070, 0x7c8c72, 0x7, 0x0, 0x0, 0x7da318, 0x2f)
	/usr/lib/golang/src/flag/flag.go:694 +0x8b
flag.(*FlagSet).String(0xc420094180, 0x7c8c72, 0x7, 0x0, 0x0, 0x7da318, 0x2f, 0xc420160060)
	/usr/lib/golang/src/flag/flag.go:707 +0x90
flag.String(0x7c8c72, 0x7, 0x0, 0x0, 0x7da318, 0x2f, 0xc42006ff28)
	/usr/lib/golang/src/flag/flag.go:714 +0x69
github.com/golang/glog.init()
	/usr/lib/golang/src/github.com/golang/glog/glog_file.go:41 +0x148
github.com/zieckey/simgo.init()
	/usr/lib/golang/src/github.com/zieckey/simgo/module_monitor.go:73 +0x76
main.init()
	/root/zb/src/github.com/Qihoo360/poseidon/service/meta/main.go:18 +0x33

**Comment by aidata** [comment]
[root@H5 ~]# cat /etc/redhat-release
CentOS release 6.5 (Final)
[root@H5 ~]# cat /proc/version
Linux version 2.6.32-431.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Fri Nov 22 03:15:09 UTC 2013
[root@H5 ~]# uname -r
2.6.32-431.el6.x86_64
[root@H5 ~]# go version
go version go1.7.3 linux/amd64

**Comment by guojun1992** [comment]
hi @aidata @cloudscode 在poseidon中搜索只有[https://github.com/golang/glog/blob/master/glog_file.go#L41](https://github.com/golang/glog/blob/master/glog_file.go#L41)依赖有声明log_dir flag，这个库比较通用，根据报错信息我认为应该是依赖的第三方simgo（这个框架中也引用glog会初始化一次log_dir flag）和glog（本身也会初始化log_dir flag）之间的命名冲突，这个问题在我们测试时一次都没发生，我们接下来会继续跟进解决这个问题，这个issue暂时不close。

付我们的测试golang 版本
$ go version
go version go1.7.1 linux/amd64

**Comment by cloudscode** [comment]
@guojun1992  谢谢！ 将go换成1.7.1并重新编译，结果运行时还是同样错误。

**Comment by guojun1992** [comment]
@cloudscode @aidata 
尝试 对idgenerator进行单独编译，看看报错吗？
``` bash
cd service/idgenerator && sh build.sh
```

**Comment by aidata** [comment]
这个能编译过去，没报错。



aidata@163.com
 
From: Viktor
Date: 2017-01-16 11:42
To: Qihoo360/poseidon
CC: aidata; Mention
Subject: Re: [Qihoo360/poseidon] idgenerator flag redefined: log_dir (#10)
@cloudscode @aidata
尝试 对idgenerator进行单独编译，看看报错吗？
cd service/idgenerator && sh build.sh

**Comment by cloudscode** [comment]
编译可以成功，运行时会出错。

**Comment by guojun1992** [comment]
@cloudscode @aidata 这个问题我们在linux 宿主机多次测试没有任何问题，但是在windows测试出现过，你们是在windows虚拟机？还是？请提供一个详细的环境和测试过程。

**Comment by zieckey** [comment]
@guojun1992 aidata在上面贴了，是linux环境。

<pre>
[root@H5 ~]# cat /etc/redhat-release
CentOS release 6.5 (Final)
[root@H5 ~]# cat /proc/version
Linux version 2.6.32-431.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Fri Nov 22 03:15:09 UTC 2013
[root@H5 ~]# uname -r
2.6.32-431.el6.x86_64
[root@H5 ~]# go version
go version go1.7.3 linux/amd64
</pre>

**Comment by guojun1992** [comment]
@cloudscode @aidata 这个问题我们做过的几轮测试都没遇到比较特殊，这里聊效率太低，加QQ群详细聊一下，有结果了我们再在这里更新解决方案

**Comment by liwei-ch** [comment]
原因就是glog模块存在于多个路径下；
解决办法：
* 删除多余的glog路径，建议保留service/vendor/github.com/golang/glog；
或者
* 重新设置$GOPATH环境变量，建议$GOPATH只设置一个目录路径
