### ISSUE TITLE
可视化界面

### ISSUE THREAD

**Issue by wubo2cyp** [Qihoo360/poseidon#12]
poseidon现在是否有提供一个可视化的界面用来查看当前的任务进度等信息？

**Comment by zieckey** [comment]
抱歉，目前没有这个功能。

**Comment by liwei-ch** [comment]
当前可以查看index-0.1/index/log/YYYY-MM-DD.log，通过日志来查看mr的进度；
hadoop自身提供有关于mr任务的状态界面；
后续我们提供一个结合hadoop系统的demo及文档
