### ISSUE TITLE
Poseidon遇到的问题

### ISSUE THREAD

**Issue by jwongo** [Qihoo360/poseidon#13]
快速开始索引的是TAB数据，我尝试索引JSON格式数据
修改dist/index-0.1/etc/test.json，把data_format改为JSON（这里应该还有其他地方需要配置，求文档）
执行docformat，index都没问题，但是sh test.sh xxx 查不出数据。

问题求助
1.如何索引JSON格式数据
2.如何在Hadoop集群中运行，而不是“local_mock”:true
3.如何进行模糊搜索、是否支持聚合查询

十分感谢

**Comment by allen-bigdata** [comment]
按照官方的步骤，我也同样查不出数据

**Comment by jwongo** [comment]
官方的快速开始文档，索引weibo_data数据，这个可以查到，不过通过sh test.sh 查出来的数据是编码过的。

**Comment by allen-bigdata** [comment]
索引weibo_data数据，这个也查看不到数据，不知道为什么

**Comment by guojun1992** [comment]
@jwongo 是这样的，在我们生产环境中来自客户端的日志并非全都是理想化的数据，比如编码，特殊符号等等，这些都可能造成传给前端渲染数据的json格式错误，所以我们将原始数据base64encode，具体代码看这里[https://github.com/Qihoo360/poseidon/blob/master/service/searcher/poseidon/doc_gz_client.go#L60](https://github.com/Qihoo360/poseidon/blob/master/service/searcher/poseidon/doc_gz_client.go#L60)
如果不需要，可以做二次开发，删除base64encode逻辑即可

**Comment by allen-bigdata** [comment]
有Q群吗，这样可以方便讨论出现的问题

**Comment by jwongo** [comment]
@guojun1992 谢谢回答，能否回答下第一条提出的几个问题。
正如@thbqlf所说，有没有官方的交流群，大家一起解决遇到的问题。

**Comment by liwei-ch** [comment]
问题1：可以先仔细看https://github.com/Qihoo360/poseidon/blob/master/docs/config.md
若还有不清楚的地方，我们后续补充下如何针对json的日志格式构建索引；
问题2：相关wiki我们会抽时间补上；

**Comment by guojun1992** [comment]
@jwongo 模糊查询和聚合查询，字段过滤等功能我们内部用的版本已经做了，因为时间问题只开源了核心功能，后期可以考虑开源，实现逻辑很简单，在现有的开源逻辑之上将关键词灌入数据库，先进行"like %key%"模糊匹配，后面步骤都是一样的可以在此基础自己实现，但是需要注意的是"like %key%"在关系型数据库是用不到索引的在不用第三方搜索引擎(比如sphinx等)配合RMDB时需要控制数据量，我们内部使用的是greenplum(底层是pgsql集群)，如果这块实现有问题再仔细交流

**Comment by zieckey** [comment]
嗯，关于模糊查询，我们目前使用greenplum的like SQL语句简单实现的，在query总量为百亿级时，效果还凑活，如果query数再多时，需要优化greenplum或重新设计模糊查询子模块。

另外，关于实时过滤模块，我们目前使用的是一个内部组件，用C++实现的布尔表达式判断库，这个库，我们也在考虑是否在今年开源出来。当前我们内部是基于这个库实现了一个过滤模块的微服务，开源版本暂时没有开放出来。

如果大家有什么好的想法，欢迎讨论。
谢谢~

**Comment by jwongo** [comment]
最新run_with_hadoop.md文档 4.1 docformat部署
sh bin/demo.sh weibo_data.txt 这个脚本会写入到本地文件系统，没有写入到HDFS

ps:最近星星增了好多，谢谢开源~v~

**Comment by liwei-ch** [comment]
@jwongo run_with_hadoop.md文档还在完善中，请稍等一段时间

**Comment by dunixd** [comment]
docformat入hdfs文档已经更新https://github.com/Qihoo360/poseidon/blob/master/docs/run_with_hadoop.md

**Comment by jwongo** [comment]
最后一步测试 sh test.sh [token]
同一个参数多次查询结果不同，"data"：返回值在变；
单节点可以命中的token，在这里返回 [ ] 或者 curl: (52) Empty reply from server。

**Comment by guojun1992** [comment]
@jwongo curl: (52) Empty reply from server。请在curl header头加Expect:，将结果和curl请求贴一下

**Comment by liwei-ch** [comment]
@thbqlf  @jwongo  qq群：21557451

**Comment by zieckey** [comment]
@liwei-ch 咱们把qq群添加到wiki中吧。
