### ISSUE TITLE
请问一下，poseidon和es有什么区别吗，谢谢

### ISSUE THREAD

**Issue by junneyang** [Qihoo360/poseidon#22]

**Comment by guojun1992** [comment]
es缺陷主要有两点

1. 百亿千亿数据没问题，但是支撑不了百万亿（上百PB）数据量
2. 如此海量数据需要另存一份，占用资源太多

[https://github.com/Qihoo360/poseidon/blob/master/docs/design_detail.pdf](https://github.com/Qihoo360/poseidon/blob/master/docs/design_detail.pdf)
看下PPT上面有当时对es做的测试和考量
