### ISSUE TITLE
说几个快速开始的问题

### ISSUE THREAD

**Issue by chy373** [Qihoo360/poseidon#6]
1. 在mac OSX 系统下，```cp -r``` 命令是与linux上不同的，导致service目录下几个微服务的打包到dist下的文件都是没有保留目录结构的，没有```/bin```, ```/conf```, ```/log```目录，我暂时的解决办法是用了```rsync -r```命令。
2. service中proxy和searcher目录中的serverctl文件中的$APP变量都有poseidon前缀，与```go build```生成的可执行文件名不同，导致serverctl start找不到对应文件。

我在我的[fork](https://github.com/chy373/poseidon)下做了修改，需要的话我可以pull request。

**Comment by liwei-ch** [comment]
好的，麻烦pull request，我们看下
也请@guojun1992 关注下

**Comment by liwei-ch** [comment]
@guojun1992

**Comment by guojun1992** [comment]
hi @chy373 ,如我们之前沟通，目前不考虑系统兼容，我们已经修改快速开始wiki
[https://github.com/Qihoo360/poseidon/blob/master/docs/get_started.md](https://github.com/Qihoo360/poseidon/blob/master/docs/get_started.md)

我们的生产环境和测试环境均是64位Liunx,快速开始建议也在同样的环境中测试。
cat /etc/redhat-release
CentOS release 6.2 (Final)

第二个命名问题也已经提交修改
